
SELECT cod_aluno, nome
FROM taluno
WHERE estato =  'rs'


SELECT cod_contrato,data, total, desconto + 10
FROM tcontrato
WHERE total >= desconto +10;

>> inicio<<

SELECT * FROM TALUNO;

ALTER TABLE taluno ADD ESTADO CHAR(2) DEFAULT 'RS';

ALTER TABLE taluno ADD salario number(8,2) DEFAULT 1620;

ALTERar  salarios e estados pelo cod aluno

UPDATE taluno SET
estado = 'GO', salario = 4800
WHERE cod_aluno = 1;

UPDATE taluno SET
estado = 'AC', salario = 800
WHERE cod_aluno = 2;

UPDATE taluno SET
estado = 'MT', salario = 3000
WHERE cod_aluno = 3;

UPDATE taluno SET
estado = 'SP',
salario = 2800
WHERE cod_aluno = 4;

SELECT * FROM TALUNO;

COMMIT;

usando WHERE


SELECT * FROM taluno
WHERE ESTADO <> 'RS'
AND salario <= 2000
ORDER BY salario DESC;

INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (SEQ_ALUNO.NEXTVAL, 'VALDO', 'DOIS IRMAOS');

INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (SEQ_ALUNO.NEXTVAL, 'ALDO', 'QUATRO IRMAOS');

SELECT * FROM TALUNO;

UPDATE taluno SET
ESTADO = 'SP', SALARIO = 900, nome = 'PEDRO'
WHERE COD_ALUNO = 25;


SELECT ESTADO, SALARIO, NOME FROM TALUNO
ORDER BY ESTADO, SALARIO DESC;

----

ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE - 1000;

--REDUÇAO DE DATA
SELECT SYSDATE - SYSDATE - 100 FROM DUAL;

--
SELECT * FROM TALUNO

UPDATE taluno SET
cep = '9000000'
WHERE COD_ALUNO = 24;

UPDATE taluno SET
NASCIMENTO = '01/01/2000'
WHERE COD_ALUNO = 2;


SELECT * FROM TALUNO


SELECT cod_aluno, nascimento, Trunc(nascimento)AS nascimento, nome
FROM taluno
WHERE Trunc(nascimento) = '01/07/2014';

SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO), NOME
FROM TALUNO
WHERE NASCIMENTO
BETWEEN TO DATE('01/01/2014 09:00','DD/MM/YYYY HH24:MI')
AND TO DATE('01/01/2014 10:00','DD/MM/YYYY HH24:MI')

---

SELECT COD_CONTRATO, DATA, TOTAL,
  DESCONTO, DESCONTO + 1000 AS CALCULO
FROM TCONTRATO
WHERE TOTAL <= DESCONTO +1000;

SELECT * FROM TCONTRATO;


UPDATE TCONTRATO SET
DESCONTO = NULL
WHERE COD_CONTRATO =2;

SELECT * FROM TCONTRATO
WHERE DESCONTO IS NULL;

SELECT * FROM TCONTRATO
WHERE DESCONTO IS NOT NULL;

SELECT * FROM TCONTRATO
WHERE DESCONTO BETWEEN 0 AND 10;

--COMANDOS NVL--
--nvl 0> colunar com valor null
--between => entre
SELECT COD_CONTRATO, TOTAL, DESCONTO, Nvl(DESCONTO, 0)
FROM TCONTRATO
WHERE Nvl(DESCONTO,0) BETWEEN 0 AND 10;

--Mesmo efeito do between

SELECT * FROM TCONTRATO
WHERE DESCONTO >= 0
AND DESCONTO <= 10
OR DESCONTO IS NULL;

--in /// not in

SELECT * FROM TITEM
WHERE COD_CURSO IN (1, 2, 3);

SELECT * FROM TITEM
WHERE COD_CURSO NOT IN  (1, 2, 3);

INSERT INTO TCURSO VALUES (5, 'WINDOWS', 1000, 50);

-- CURSOS NAO VENDIDOS
SELECT * FROM TCURSO
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TITEM)

-- CURSOS VENDIDOS
SELECT * FROM TCURSO
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM)

--EQUIVALENTE AO SELECT IN
SELECT *  FROM TITEM
WHERE COD_CURSO = 1
OR COD_CURSO = 2
OR COD_CURSO = 4;

--somente onde a segunda letra seja A

SELECT * FROM TALUNO WHERE NOME LIKE '_A%'

SELECT * FROM TCURSO WHERE NOME LIKE '%JAVA%' --INICIA
SELECT * FROM TCURSO WHERE NOME LIKE '%FACES'   -- TERMINA

COMMIT

SELECT * FROM TCURSO;

ALTER TABLE TCURSO ADD  PRE_REQ INTEGER;

UPDATE TCURSO SET
PRE_REQ = 1
WHERE COD_CURSO = 2;

UPDATE TCURSO SET
PRE_REQ = 3
WHERE COD_CURSO = 4;

--CURSOS SEM PRE REQUISITO

SELECT * FROM TCURSO WHERE PRE_REQ IS NULL

--CURSOS COM  PRE REQUISITO

SELECT * FROM TCURSO WHERE PRE_REQ IS NOT NULL


-- ORDEM DE EXECUÇAO COM PARENTESES OU SEM
SELECT  * FROM TCURSO
WHERE VALOR > 750
OR VALOR < 1000
AND CARGA_HORARIA = 25

SELECT  * FROM TCURSO
WHERE (VALOR > 750
OR VALOR < 1000 )
AND CARGA_HORARIA = 25

COMMIT













commit



